export const assetFolderFixtures = [
  ["folder-north-inbox", "north", "收件箱"],
  ["folder-north-scouting", "north", "勘景"],
  ["folder-north-visual", "north", "视觉参考"],
  ["folder-north-production", "north", "制片文件"],
  ["folder-north-sound", "north", "声音"],
  ["folder-north-final", "north", "成片"],
  ["folder-north-rights", "north", "授权文件"],
] as const

export const teamAssetFixtures = [
  {
    id: "asset-winter-main-v11",
    teamId: "north",
    projectId: "winter-coffee",
    folderId: "folder-north-final",
    name: "冬夜咖啡_主片 v11",
    kind: "视频" as const,
    mimeType: "video/mp4",
    sizeBytes: 78_643_200,
    ownerId: "account-fanxing",
    favorite: true,
    rating: 5,
    tags: ["成片", "已通过", "主片"],
    note: "审片已通过版本，作为作品集候选。",
    thumbnailUrl: "/assets/winter-coffee.png",
  },
  {
    id: "asset-station-scout-01",
    teamId: "north",
    projectId: "winter-coffee",
    folderId: "folder-north-scouting",
    name: "车站勘景参考 01",
    kind: "图片" as const,
    mimeType: "image/png",
    sizeBytes: 19_293_798,
    ownerId: "account-guyao",
    favorite: true,
    rating: 5,
    tags: ["车站", "夜景", "构图参考"],
    note: "站台纵深和顶部灯带可作为主场景构图依据。",
    thumbnailUrl: "/assets/winter-coffee.png",
  },
  {
    id: "asset-rain-equipment",
    teamId: "north",
    projectId: "winter-coffee",
    folderId: "folder-north-production",
    name: "人工雨设备清单",
    kind: "文档" as const,
    mimeType: "application/pdf",
    sizeBytes: 2_202_010,
    ownerId: "account-fanxing",
    favorite: false,
    rating: 4,
    tags: ["设备", "雨效"],
    note: "包含雨车、水泵、照明防水和现场安全物资。",
    thumbnailUrl: null,
  },
  {
    id: "asset-route-scout-video",
    teamId: "north",
    projectId: "city-walk",
    folderId: "folder-north-scouting",
    name: "路线勘景视频",
    kind: "视频" as const,
    mimeType: "video/mp4",
    sizeBytes: 41_943_040,
    ownerId: "account-guyao",
    favorite: false,
    rating: 3,
    tags: ["路线", "外景"],
    note: "",
    thumbnailUrl: "/assets/winter-coffee.png",
  },
  {
    id: "asset-blue-night-reference",
    teamId: "north",
    projectId: "blue-hour",
    folderId: "folder-north-visual",
    name: "冷调夜景参考",
    kind: "图片" as const,
    mimeType: "image/png",
    sizeBytes: 13_421_772,
    ownerId: "account-fanxing",
    favorite: true,
    rating: 4,
    tags: ["调色", "蓝调"],
    note: "",
    thumbnailUrl: "/assets/winter-coffee.png",
  },
  {
    id: "asset-station-ambience",
    teamId: "north",
    projectId: "winter-coffee",
    folderId: "folder-north-sound",
    name: "站台环境底噪",
    kind: "音频" as const,
    mimeType: "audio/wav",
    sizeBytes: 9_961_472,
    ownerId: "account-fanxing",
    favorite: false,
    rating: 3,
    tags: ["环境声", "车站"],
    note: "",
    thumbnailUrl: null,
  },
  {
    id: "asset-storyboard-v4",
    teamId: "north",
    projectId: "winter-coffee",
    folderId: "folder-north-production",
    name: "车站段落分镜 v4",
    kind: "文档" as const,
    mimeType: "application/pdf",
    sizeBytes: 9_122_611,
    ownerId: "account-fanxing",
    favorite: false,
    rating: 5,
    tags: ["分镜", "锁定"],
    note: "",
    thumbnailUrl: null,
  },
] as const
