export const breakdownFixtures = [
  [
    "br1",
    "cast",
    "顾遥",
    "主要角色",
    "夜雨戏妆发与深色造型",
    "演员 1 人，替身 1 人",
    "确认演员档期，准备完整妆发、雨戏替换服装与保暖方案",
    "选角 / 演员统筹",
    "剧本明确出现主要角色，并包含雨夜连续性要求",
    "冬夜咖啡_拍摄稿",
    "v7",
    "场 12",
    "顾遥拖着深红色硬壳行李箱，从站台尽头走出。",
    98,
  ],
  [
    "br2",
    "location",
    "旧站台",
    "拍摄场地",
    "夜景，可控灯光，允许人工雨与轨道区域拍摄",
    "站台 1 处",
    "完成场地勘景、许可、封控、电力、排水和轨道安全确认",
    "制片 / 场务",
    "场景条件涉及人工雨和轨道区域，需提前完成安全核验",
    "冬夜咖啡_拍摄稿",
    "v7",
    "场 12",
    "空荡的旧站台只剩顶灯的电流声。",
    96,
  ],
  [
    "br3",
    "art",
    "深红色硬壳行李箱",
    "主道具",
    "深红色硬壳，外观需支持近景拍摄",
    "英雄件 1 件，替换件 1 件",
    "完成采购、做旧、编号和连续性照片，替换件保持一致",
    "美术 / 道具",
    "道具由角色持续携带并进入画面近景，属于连续性主道具",
    "冬夜咖啡_拍摄稿",
    "v7",
    "场 12",
    "顾遥拖着深红色硬壳行李箱。",
    99,
  ],
  [
    "br4",
    "wardrobe",
    "顾遥夜景造型",
    "服装与造型",
    "深色风衣，雨戏妆发连续",
    "主套 1 套，替换 2 套",
    "完成试装与定妆，雨戏替换套装按湿度阶段编号并准备保暖层",
    "服装 / 化妆",
    "分镜要求人物从阴影进入顶灯区域，造型轮廓和湿发状态需连续",
    "车站段落分镜",
    "v4",
    "镜头 12-02",
    "中景跟随，人物从阴影中进入顶灯区域。",
    87,
  ],
  [
    "br5",
    "equipment",
    "人工雨夜景摄影包",
    "摄影与录音设备",
    "摄影机防雨罩、长焦组、无线跟焦、移动电源",
    "摄影包 1 套，防雨备件 1 套",
    "完成防雨测试、电池轮换、镜头除雾和无线设备频段检查",
    "摄影 / 灯光 / 录音",
    "连续人工雨覆盖五个镜头，设备需满足长时间夜景防护",
    "车站段落分镜",
    "v4",
    "镜头 12-01—12-05",
    "人工雨覆盖站台入口与人物行进区域。",
    91,
  ],
  [
    "br6",
    "special",
    "人工雨与现场安全",
    "特殊效果与安全",
    "雨车、排水、防滑垫、漏电保护、热饮与保暖区",
    "雨车 1 台，安全保障 1 组",
    "完成雨效测试、排水预案、用电隔离、人员动线和低温保障",
    "特效 / 安全 / 后勤",
    "剧本明确要求人工雨及积水反光，需要特效与安全部门联合执行",
    "冬夜咖啡_拍摄稿",
    "v7",
    "制片备注",
    "雨势渐小，地面积水反射站台顶灯。",
    94,
  ],
] as const

export const shootingDayFixtures = [
  {
    id: "shoot-day-05",
    shootDate: "2026-08-19",
    dayNumber: 5,
    title: "车站夜戏",
    status: "已完成" as const,
    originalTimezone: "Asia/Shanghai",
  },
  {
    id: "shoot-day-06",
    shootDate: "2026-08-20",
    dayNumber: 6,
    title: "站台出口与清晨补景",
    status: "已确认" as const,
    originalTimezone: "Asia/Shanghai",
  },
  {
    id: "shoot-day-07",
    shootDate: "2026-08-21",
    dayNumber: 7,
    title: "室内咖啡店",
    status: "草稿" as const,
    originalTimezone: "Asia/Shanghai",
  },
] as const

export const callSheetFixtures = [
  {
    id: "sd-05",
    shootingDayId: "shoot-day-05",
    date: "8 月 19 日",
    day: "拍摄第 5 天",
    title: "车站夜戏",
    status: "已发布" as const,
    crewCall: "16:30",
    firstShot: "19:00",
    wrap: "次日 03:30",
    weather: "小雨转阴 · 24°C",
    sunrise: "05:31",
    sunset: "18:43",
    basecamp: "北站停车场 B 区",
    location: "旧北站 2 号站台",
    hospital: "市二院急诊 · 4.2 km",
    scenes: [
      {
        scene: "12",
        set: "旧站台 / 外 / 夜",
        pages: "2 3/8",
        description: "顾遥拖着行李箱进入站台，等待未进站的列车",
        cast: "1",
      },
      {
        scene: "13A",
        set: "站台出口 / 外 / 夜",
        pages: "1 1/8",
        description: "雨停后，顾遥回望站台",
        cast: "1, 4",
      },
    ],
    cast: [
      { name: "顾遥", role: "顾遥", pickup: "15:20", makeup: "15:50", set: "18:30" },
      { name: "陈锋", role: "站务员", pickup: "17:00", makeup: "17:30", set: "20:40" },
    ],
    departments: [
      { name: "摄影组", call: "16:00", note: "雨戏防护测试后入场" },
      { name: "灯光组", call: "15:30", note: "先完成轨道区用电隔离" },
      { name: "美术组", call: "16:30", note: "核对行李箱连续性" },
    ],
    equipment: [
      { name: "雨车", quantity: "1 台", source: "北岸特效", note: "17:30 完成试雨" },
      { name: "摄影机防雨包", quantity: "2 套", source: "器材组", note: "一套备用" },
    ],
    safety: [
      {
        level: "高",
        item: "人工雨与轨道区域",
        owner: "安全员 / 场务",
        action: "铺设防滑垫、配置漏电保护，未经场务放行不得进入轨道区",
      },
    ],
    transport: [
      {
        item: "全组班车",
        time: "15:30",
        route: "制作中心 → 北站停车场 B 区",
        owner: "交通组",
        note: "15:20 停止等候",
      },
    ],
    catering: [{ meal: "热餐", time: "18:00", location: "基地东侧", note: "夜宵 00:30" }],
    keyContacts: [
      { name: "崔岚", role: "现场制片", phone: "138-0000-1205", note: "现场总协调" },
      { name: "周弥", role: "安全员", phone: "138-0000-1210", note: "轨道区放行" },
    ],
    nextDayPreview: {
      date: "8 月 20 日",
      title: "站台出口与清晨补景",
      scenes: "14",
      cast: "顾遥",
      note: "04:30 全组集合，注意夜转晨连续性",
    },
  },
  {
    id: "sd-06",
    shootingDayId: "shoot-day-06",
    date: "8 月 20 日",
    day: "拍摄第 6 天",
    title: "站台出口与清晨补景",
    status: "草稿" as const,
    crewCall: "04:30",
    firstShot: "05:20",
    wrap: "11:30",
    weather: "多云 · 22°C",
    sunrise: "05:32",
    sunset: "18:42",
    basecamp: "北站停车场 A 区",
    location: "旧北站出口",
    hospital: "市二院急诊 · 4.0 km",
    scenes: [
      {
        scene: "14",
        set: "车站出口 / 外 / 晨",
        pages: "1 4/8",
        description: "顾遥在晨光中离开车站",
        cast: "1",
      },
    ],
    cast: [
      { name: "顾遥", role: "顾遥", pickup: "03:50", makeup: "04:10", set: "05:00" },
    ],
    departments: [],
    equipment: [],
    safety: [],
    transport: [],
    catering: [],
    keyContacts: [],
    nextDayPreview: { date: "", title: "", scenes: "", cast: "", note: "" },
  },
  {
    id: "sd-07",
    shootingDayId: "shoot-day-07",
    date: "8 月 21 日",
    day: "拍摄第 7 天",
    title: "室内咖啡店",
    status: "待确认" as const,
    crewCall: "08:00",
    firstShot: "09:30",
    wrap: "19:00",
    weather: "晴 · 27°C",
    sunrise: "05:33",
    sunset: "18:41",
    basecamp: "冬叶咖啡后巷",
    location: "冬叶咖啡馆",
    hospital: "中心医院急诊 · 2.8 km",
    scenes: [
      {
        scene: "18",
        set: "咖啡店 / 内 / 日",
        pages: "3 2/8",
        description: "顾遥与林森第一次正面交谈",
        cast: "1, 2",
      },
    ],
    cast: [
      { name: "顾遥", role: "顾遥", pickup: "06:50", makeup: "07:20", set: "09:00" },
      { name: "林森", role: "林森", pickup: "07:00", makeup: "07:30", set: "09:00" },
    ],
    departments: [],
    equipment: [],
    safety: [],
    transport: [],
    catering: [],
    keyContacts: [],
    nextDayPreview: { date: "", title: "", scenes: "", cast: "", note: "" },
  },
] as const

export const executionStageFixtures = [
  {
    id: "exec-pre",
    name: "前期准备",
    startsAt: "2026-08-10T01:00:00.000Z",
    endsAt: "2026-08-18T10:00:00.000Z",
    originalTimezone: "Asia/Shanghai",
    progress: 100,
    owner: "繁星",
    state: "已完成" as const,
    note: "脚本锁定、场地许可、演员与核心供应商确认",
    resources: [{ id: "producer-fanxing", type: "crew" as const, name: "繁星" }],
  },
  {
    id: "exec-shoot",
    name: "拍摄执行",
    startsAt: "2026-08-19T08:30:00.000Z",
    endsAt: "2026-08-21T11:00:00.000Z",
    originalTimezone: "Asia/Shanghai",
    progress: 68,
    owner: "崔岚",
    state: "进行中" as const,
    note: "车站夜戏是当前关键路径",
    resources: [
      { id: "cast-guyao", type: "cast" as const, name: "顾遥" },
      { id: "old-north-station", type: "location" as const, name: "旧北站" },
      { id: "rain-rig-1", type: "equipment" as const, name: "雨车 1 号" },
    ],
  },
  {
    id: "exec-pickup",
    name: "补拍与收尾",
    startsAt: "2026-08-22T01:00:00.000Z",
    endsAt: "2026-08-23T11:00:00.000Z",
    originalTimezone: "Asia/Shanghai",
    progress: 10,
    owner: "林乔",
    state: "未开始" as const,
    note: "根据主拍素材完整度决定补拍范围",
    resources: [{ id: "cast-guyao", type: "cast" as const, name: "顾遥" }],
  },
  {
    id: "exec-post",
    name: "后期交付",
    startsAt: "2026-08-24T01:00:00.000Z",
    endsAt: "2026-09-03T10:00:00.000Z",
    originalTimezone: "Asia/Shanghai",
    progress: 5,
    owner: "沈默",
    state: "进行中" as const,
    note: "同步整理素材与代理文件，粗剪结构准备中",
    resources: [{ id: "editor-shenmo", type: "crew" as const, name: "沈默" }],
  },
] as const

export const reviewFileFixtures = [
  ["main-v12", "冬夜咖啡_主片", "v12", "video", "审阅中", "00:30"],
  ["main-v11", "冬夜咖啡_主片", "v11", "video", "已通过", "00:30"],
  ["social", "社交媒体竖版", "v4", "video", "处理中", "00:15"],
] as const

export const reviewFolderFixtures = [
  ["delivery", "客户交付"],
  ["archive", "已确认版本"],
] as const

export const reviewCommentFixtures = [
  [
    "c1",
    "main-v12",
    "account-guyao",
    "00:07.120",
    "开场站台空镜可以再多留 8 帧，让环境声先建立起来。",
    "open",
  ],
  [
    "c2",
    "main-v12",
    "account-fanxing",
    "00:12.840",
    "杯子特写的焦点很好，建议把下一镜的切点跟蒸汽上升对齐。",
    "open",
  ],
  [
    "c3",
    "main-v12",
    "account-songlan",
    "00:18.420",
    "这里演员视线与反打存在轻微跳轴，先比较 v11 的备用镜头。",
    "open",
  ],
  [
    "c4",
    "main-v12",
    "account-guyao",
    "00:24.080",
    "音乐收束已经调整，当前节奏可以保留。",
    "resolved",
  ],
] as const
