export const workspaceTaskFixtures = [
  {
    id: "task-confirm-cast",
    teamId: "north",
    projectId: "winter-coffee",
    title: "确认车站夜戏演员与供应商",
    dueDate: "2026-08-28",
    status: "进行中" as const,
    target: "breakdown",
  },
  {
    id: "task-publish-call-sheet",
    teamId: "north",
    projectId: "winter-coffee",
    title: "发布车站夜戏通告",
    dueDate: "2026-08-29",
    status: "待开始" as const,
    target: "schedule",
  },
  {
    id: "task-review-route",
    teamId: "north",
    projectId: "city-walk",
    title: "复核路线勘景候选",
    dueDate: "2026-08-30",
    status: "等待他人" as const,
    target: "breakdown",
  },
  {
    id: "task-lock-script",
    teamId: "north",
    projectId: "winter-coffee",
    title: "锁定拍摄稿 v7",
    dueDate: "2026-08-27",
    status: "已完成" as const,
    target: "scripts",
  },
  {
    id: "task-review-mercury",
    teamId: "midnight",
    projectId: "mercury-perfume",
    title: "整理主片 v12 审片意见",
    dueDate: "2026-08-30",
    status: "待开始" as const,
    target: "reviews",
  },
] as const

export const calendarEventFixtures = [
  {
    id: "event-cast-confirmation",
    teamId: "north",
    projectId: "winter-coffee",
    title: "演员与供应商确认",
    startsAt: "2026-08-28T02:00:00.000Z",
    target: "breakdown",
  },
  {
    id: "event-call-sheet",
    teamId: "north",
    projectId: "winter-coffee",
    title: "车站夜戏通告协同",
    startsAt: "2026-08-28T08:30:00.000Z",
    target: "schedule",
  },
  {
    id: "event-script-review",
    teamId: "north",
    projectId: "winter-coffee",
    title: "拍摄稿 v7 确认",
    startsAt: "2026-08-28T11:00:00.000Z",
    target: "scripts",
  },
  {
    id: "event-route-scout",
    teamId: "north",
    projectId: "city-walk",
    title: "路线勘景",
    startsAt: "2026-09-02T01:30:00.000Z",
    target: "breakdown",
  },
] as const

export const workspaceNoteFixtures = [
  {
    id: "note-rain-execution",
    teamId: "north",
    projectId: "winter-coffee",
    title: "车站雨效执行提醒",
    body: "确认雨车覆盖范围，现场准备两套防水方案。演员鞋底与轨道区域需要额外防滑。",
    kind: "note" as const,
    pinned: true,
  },
  {
    id: "note-client-feedback",
    teamId: "north",
    projectId: "city-walk",
    title: "客户反馈待整理",
    body: "路线段需要更多人物互动镜头，下一版分镜集中处理。",
    kind: "note" as const,
    pinned: false,
  },
  {
    id: "sticky-lens",
    teamId: "north",
    projectId: null,
    title: "镜头测试",
    body: "带 35mm 和 50mm 两组镜头，提前测试雨幕逆光。",
    kind: "sticky" as const,
    pinned: true,
  },
  {
    id: "sticky-catering",
    teamId: "north",
    projectId: null,
    title: "夜戏餐食",
    body: "确认夜宵数量与两位素食成员。",
    kind: "sticky" as const,
    pinned: false,
  },
] as const
